filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/app.log  # Correct path

output.logstash:
  hosts: ["logstash:5044"]  # Instead of external IP

setup.kibana:
  host: "http://3.89.229.219:5601"

monitoring.enabled: false


logging:
  level: info
  to_files: true
  files:
    path: "/var/log/filebeat"
    name: filebeat
    keepfiles: 7
    permissions: 0644
